In [1]:
# Import dependencies
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# The path to the World Happiness CSV file
shelters_file = "data/petfinder_shelters.csv"

# Read the World Happiness data into pandas
original_shelters_df = pd.read_csv(shelters_file, delimiter = ';')
original_shelters_df

ParserError: Error tokenizing data. C error: Expected 1 fields in line 1624, saw 2

In [3]:
# Inspect the data types
original_happiness_df.dtypes

Country name                                                 object
Year                                                          int64
Life Ladder                                                 float64
Log GDP per capita                                          float64
Social support                                              float64
Healthy life expectancy at birth                            float64
Freedom to make life choices                                float64
Generosity                                                  float64
Perceptions of corruption                                   float64
Positive affect                                             float64
Negative affect                                             float64
Confidence in national government                           float64
Democratic Quality                                          float64
Delivery Quality                                            float64
Standard deviation of ladder by country-year                float64
Standard deviation/Mean of ladder by country-year           float64
GINI index (World Bank estimate)                            float64
GINI index (World Bank estimate), average 2000-16           float64
gini of household income reported in Gallup, by wp5-year    float64
Most people can be trusted, Gallup                          float64
Most people can be trusted, WVS round 1981-1984             float64
Most people can be trusted, WVS round 1989-1993             float64
Most people can be trusted, WVS round 1994-1998             float64
Most people can be trusted, WVS round 1999-2004             float64
Most people can be trusted, WVS round 2005-2009             float64
Most people can be trusted, WVS round 2010-2014             float64
dtype: object

In [4]:
# Create a pandas DataFrame
clean_happiness_df = pd.DataFrame(original_happiness_df)
clean_happiness_df

,Country name,Year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,...,GINI index (World Bank estimate),"GINI index (World Bank estimate), average 2000-16","gini of household income reported in Gallup, by wp5-year","Most people can be trusted, Gallup","Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014"
0,Afghanistan,2008,3.723590,7.168690,0.450662,50.799999,0.718114,0.177889,0.881686,0.517637,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,2009,4.401778,7.333790,0.552308,51.200001,0.678896,0.200178,0.850035,0.583926,...,NaN,NaN,0.441906,0.286315,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,2010,4.758381,7.386629,0.539075,51.599998,0.600127,0.134353,0.706766,0.618265,...,NaN,NaN,0.327318,0.275833,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,2011,3.831719,7.415019,0.521104,51.919998,0.495901,0.172137,0.731109,0.611387,...,NaN,NaN,0.336764,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,2012,3.782938,7.517126,0.520637,52.240002,0.530935,0.244273,0.775620,0.710385,...,NaN,NaN,0.344540,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1699,Zimbabwe,2014,4.184451,7.562753,0.765839,52.380001,0.642034,-0.048634,0.820217,0.725214,...,NaN,0.432,0.601080,NaN,NaN,NaN,NaN,0.116683,NaN,0.082942
1700,Zimbabwe,2015,3.703191,7.556052,0.735800,53.799999,0.667193,-0.097354,0.810457,0.715079,...,NaN,0.432,0.655137,NaN,NaN,NaN,NaN,0.116683,NaN,0.082942
1701,Zimbabwe,2016,3.735400,7.538829,0.768425,54.400002,0.732971,-0.068105,0.723612,0.737636,...,NaN,0.432,0.596690,NaN,NaN,NaN,NaN,0.116683,NaN,0.082942
1702,Zimbabwe,2017,3.638300,7.549491,0.754147,55.000000,0.752826,-0.069670,0.751208,0.806428,...,NaN,0.432,0.581484,NaN,NaN,NaN,NaN,0.116683,NaN,0.082942
1703,Zimbabwe,2018,3.616480,7.553395,0.775388,55.599998,0.762675,-0.038384,0.844209,0.710119,...,NaN,0.432,0.541772,NaN,NaN,NaN,NaN,0.116683,NaN,0.082942

In [5]:
# Filter the DataFrame to only the year 2010
clean_happiness_df = clean_happiness_df.loc[clean_happiness_df["Year"] == 2010, :]
clean_happiness_df

,Country name,Year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,...,GINI index (World Bank estimate),"GINI index (World Bank estimate), average 2000-16","gini of household income reported in Gallup, by wp5-year","Most people can be trusted, Gallup","Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014"
2,Afghanistan,2010,4.758381,7.386629,0.539075,51.599998,0.600127,0.134353,0.706766,0.618265,...,NaN,NaN,0.327318,0.275833,NaN,NaN,NaN,NaN,NaN,NaN
13,Albania,2010,5.268937,9.203032,0.733152,66.400002,0.568958,-0.175367,0.726262,0.647908,...,NaN,0.303250,0.543528,0.201118,NaN,NaN,0.243243,0.232000,NaN,NaN
22,Algeria,2010,5.463567,9.462701,NaN,64.500000,0.592696,-0.229078,0.618038,NaN,...,NaN,0.276000,0.492713,NaN,NaN,NaN,NaN,0.107644,NaN,0.179286
37,Argentina,2010,6.441067,9.836924,0.926799,67.300003,0.730258,-0.121725,0.854695,0.846136,...,0.430,0.460938,0.366742,0.228952,0.270073,0.223553,0.170844,0.150154,0.174058,0.193531
50,Armenia,2010,4.367811,8.810287,0.660342,65.199997,0.459257,-0.162075,0.890629,0.509669,...,0.300,0.319250,0.385238,NaN,NaN,NaN,0.235000,NaN,NaN,0.109136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1633,Uzbekistan,2010,5.095342,8.352248,0.903226,63.200001,NaN,-0.031256,0.518720,0.775874,...,NaN,0.348000,0.330614,NaN,NaN,NaN,NaN,NaN,NaN,0.139224
1646,Venezuela,2010,7.478455,9.713838,0.931576,65.699997,0.768257,-0.166679,0.754269,0.861522,...,NaN,0.497167,0.313196,0.129567,NaN,NaN,0.133333,0.158333,NaN,NaN
1659,Vietnam,2010,5.295781,8.391214,0.786611,66.500000,0.831494,-0.003416,0.742637,0.685243,...,0.393,0.362750,0.479870,0.269085,NaN,NaN,NaN,0.387000,0.510054,NaN
1670,Yemen,2010,4.350313,8.407098,0.726612,54.299999,0.659284,-0.108985,0.853403,0.582427,...,NaN,0.357000,0.403628,NaN,NaN,NaN,NaN,NaN,NaN,0.385000
1695,Zimbabwe,2010,4.681570,7.296330,0.856638,46.700001,0.664718,-0.066457,0.828361,0.747702,...,NaN,0.432000,0.680030,NaN,NaN,NaN,NaN,0.116683,NaN,0.082942

In [6]:
# Rename columns to exclude capital letters and spaces in preparation to loading into SQL database.
renamed_happiness_df = clean_happiness_df.rename(columns={"Country name":"country", "Year":"year", 
                                             "Life Ladder":"life_ladder", "Log GDP per capita":"log_gdp_per_capita",
                                            "Social support":"social_support", "Healthy life expectancy at birth":"healthy_life_expectancy_at_birth",
                                              "Freedom to make life choices":"freedom_to_make_life_choices", "Generosity":"generosity",
                                                  "Perceptions of corruption":"perceptions_of_corruption", "Positive affect":"positive_affect",
                                                     "Negative affect":"negative_affect", "GINI index (World Bank estimate)":"gini_index_(world_bank_estimate)",
                                                     "GINI index (World Bank estimate), average 2000-16":"gini_index_(world_bank_estimate),_average_2000-16",
                                                     "gini of household income reported in Gallup, by wp5-year":"gini_of_household_income_reported_in_gallup,_by_wp5-year",
                                                     "Most people can be trusted, Gallup":"most_people_can_be_trusted,_gallup",
                                                     "Most people can be trusted, WVS round 1981-1984":"most_people_can_be_trusted,_wvs_round_1981-1984",
                                                     "Most people can be trusted, WVS round 1989-1993":"most_people_can_be_trusted,_wvs_round_1989-1993",
                                                     "Most people can be trusted, WVS round 1994-1998":"most_people_can_be_trusted,_wvs_round_1994-1998",
                                                     "Most people can be trusted, WVS round 1999-2004":"most_people_can_be_trusted,_wvs_round_1999-2004",
                                                     "Most people can be trusted, WVS round 2005-2009":"most_people_can_be_trusted,_wvs_round_2005-2009",
                                                     "Most people can be trusted, WVS round 2010-2014":"most_people_can_be_trusted,_wvs_round_2010-2014"})

renamed_happiness_df.head()

,country,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,...,gini_index_(world_bank_estimate),"gini_index_(world_bank_estimate),_average_2000-16","gini_of_household_income_reported_in_gallup,_by_wp5-year","most_people_can_be_trusted,_gallup","most_people_can_be_trusted,_wvs_round_1981-1984","most_people_can_be_trusted,_wvs_round_1989-1993","most_people_can_be_trusted,_wvs_round_1994-1998","most_people_can_be_trusted,_wvs_round_1999-2004","most_people_can_be_trusted,_wvs_round_2005-2009","most_people_can_be_trusted,_wvs_round_2010-2014"
2,Afghanistan,2010,4.758381,7.386629,0.539075,51.599998,0.600127,0.134353,0.706766,0.618265,...,NaN,NaN,0.327318,0.275833,NaN,NaN,NaN,NaN,NaN,NaN
13,Albania,2010,5.268937,9.203032,0.733152,66.400002,0.568958,-0.175367,0.726262,0.647908,...,NaN,0.303250,0.543528,0.201118,NaN,NaN,0.243243,0.232000,NaN,NaN
22,Algeria,2010,5.463567,9.462701,NaN,64.500000,0.592696,-0.229078,0.618038,NaN,...,NaN,0.276000,0.492713,NaN,NaN,NaN,NaN,0.107644,NaN,0.179286
37,Argentina,2010,6.441067,9.836924,0.926799,67.300003,0.730258,-0.121725,0.854695,0.846136,...,0.43,0.460938,0.366742,0.228952,0.270073,0.223553,0.170844,0.150154,0.174058,0.193531
50,Armenia,2010,4.367811,8.810287,0.660342,65.199997,0.459257,-0.162075,0.890629,0.509669,...,0.30,0.319250,0.385238,NaN,NaN,NaN,0.235000,NaN,NaN,0.109136

In [7]:
# Reset the index to country
#happiness_data = renamed_happiness_df.set_index("country")
#happiness_data

In [8]:
happiness_data = renamed_happiness_df[["country","year","life_ladder","log_gdp_per_capita","social_support", 
                                     "healthy_life_expectancy_at_birth", "freedom_to_make_life_choices", 
                                     "generosity", "perceptions_of_corruption"]]
happiness_data.head()
#happiness_data.dtypes

,country,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption
2,Afghanistan,2010,4.758381,7.386629,0.539075,51.599998,0.600127,0.134353,0.706766
13,Albania,2010,5.268937,9.203032,0.733152,66.400002,0.568958,-0.175367,0.726262
22,Algeria,2010,5.463567,9.462701,NaN,64.500000,0.592696,-0.229078,0.618038
37,Argentina,2010,6.441067,9.836924,0.926799,67.300003,0.730258,-0.121725,0.854695
50,Armenia,2010,4.367811,8.810287,0.660342,65.199997,0.459257,-0.162075,0.890629

In [9]:
happiness_data.to_csv("data/clean_happiness.csv", index=False, header=True)

In [10]:
# Connect to local database
engine = create_engine(f'postgresql://postgres:melsie@localhost:5432/happiness_etoh_worldcup')
connection = engine.connect()
#engine.table_names()

# Load happiness csv
happiness_data.to_sql(name='happiness_data', con=engine, if_exists='append', index=False)